/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EncuestaRouteImport } from './routes/encuesta'
import { Route as AdministradorRouteImport } from './routes/administrador'
import { Route as IndexRouteImport } from './routes/index'

const EncuestaRoute = EncuestaRouteImport.update({
  id: '/encuesta',
  path: '/encuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministradorRoute = AdministradorRouteImport.update({
  id: '/administrador',
  path: '/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/encuesta': typeof EncuestaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/encuesta': typeof EncuestaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/encuesta': typeof EncuestaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/administrador' | '/encuesta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/administrador' | '/encuesta'
  id: '__root__' | '/' | '/administrador' | '/encuesta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministradorRoute: typeof AdministradorRoute
  EncuestaRoute: typeof EncuestaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/encuesta': {
      id: '/encuesta'
      path: '/encuesta'
      fullPath: '/encuesta'
      preLoaderRoute: typeof EncuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrador': {
      id: '/administrador'
      path: '/administrador'
      fullPath: '/administrador'
      preLoaderRoute: typeof AdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministradorRoute: AdministradorRoute,
  EncuestaRoute: EncuestaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
